/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package yjfile.client;

import org.junit.Test;

import java.io.IOException;

import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() throws IOException {

        try {
            YJFileClient client = new YJFileClient("");
            for (String url : client.getFileList()) {
                System.out.println(url);
            }
            assertNotEquals(0,client.getFileList().size());
        } catch (YJFileClientException e) {
            fail(e.getMessage());
        }
    }
}
